/* Service worker — generated by build.js, do not edit app/sw.js directly. */
const VERSION = '950e511734d0';
const CACHE = 'kondaki-' + VERSION;
const ASSETS = ["./","app.js","data/gansatevebelni.json","data/index.json","data/jvari.json","data/kmevebi.json","data/kurtxevani.json","data/litanioba.json","data/liturgy.json","data/matins.json","data/paraklisi.json","data/vespers.json","data/ziareba.json","fonts/fonts.css","fonts/nsg-georgian.woff2","fonts/nsg-latin-ext.woff2","fonts/nsg-latin.woff2","icons/apple-touch-icon.png","icons/icon-192.png","icons/icon-512.png","icons/maskable-512.png","index.html","manifest.webmanifest","style.css"];

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(ASSETS.map((a) => new Request(a, { cache: 'reload' }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== location.origin) return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) =>
      hit ||
      fetch(e.request).then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(e.request, copy));
        }
        return res;
      }).catch(() => (e.request.mode === 'navigate' ? caches.match('index.html') : undefined))
    )
  );
});
